import React from 'react'
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'
import type { GeneratedStatement } from './statements'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica' },
  header: { marginBottom: 20 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 12, color: '#666', marginBottom: 12 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 8 },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 4 },
  headerRow: { flexDirection: 'row', borderBottomWidth: 2, borderBottomColor: '#333', paddingVertical: 4, fontWeight: 'bold' },
  col: { flex: 1 },
  colWide: { flex: 2 },
  colRight: { flex: 1, textAlign: 'right' },
  summaryRow: { flexDirection: 'row', paddingVertical: 4 },
  summaryLabel: { flex: 2, fontWeight: 'bold' },
  summaryValue: { flex: 1, textAlign: 'right' },
  totalRow: { flexDirection: 'row', paddingVertical: 6, borderTopWidth: 2, borderTopColor: '#333', marginTop: 4 },
  totalLabel: { flex: 2, fontWeight: 'bold', fontSize: 12 },
  totalValue: { flex: 1, textAlign: 'right', fontWeight: 'bold', fontSize: 12 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#999' },
})

interface StatementPDFProps {
  statement: GeneratedStatement
  ownerName: string
  ownerNif?: string
  ownerIban?: string
  businessName: string
  currency?: string
}

function fmt(amount: number, currency = 'EUR'): string {
  return `${amount.toFixed(2)} ${currency}`
}

export function StatementPDF({
  statement,
  ownerName,
  ownerNif,
  ownerIban,
  businessName,
  currency = 'EUR',
}: StatementPDFProps) {
  const periodLabel = `${statement.periodStart} — ${statement.periodEnd}`

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Owner Statement</Text>
          <Text style={styles.subtitle}>{periodLabel}</Text>
          <Text>{businessName}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Owner</Text>
          <Text>{ownerName}</Text>
          {ownerNif && <Text>NIF: {ownerNif}</Text>}
          {ownerIban && <Text>IBAN: {ownerIban}</Text>}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Gross Revenue</Text>
            <Text style={styles.summaryValue}>{fmt(statement.totalRevenue, currency)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Expenses</Text>
            <Text style={styles.summaryValue}>-{fmt(statement.totalExpenses, currency)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Commission</Text>
            <Text style={styles.summaryValue}>-{fmt(statement.totalCommission, currency)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Net Amount</Text>
            <Text style={styles.totalValue}>{fmt(statement.netAmount, currency)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Reservation Breakdown</Text>
          <View style={styles.headerRow}>
            <Text style={styles.colWide}>Guest / Property</Text>
            <Text style={styles.col}>Dates</Text>
            <Text style={styles.colRight}>Revenue</Text>
            <Text style={styles.colRight}>Expenses</Text>
            <Text style={styles.colRight}>Commission</Text>
            <Text style={styles.colRight}>Net</Text>
          </View>
          {statement.breakdown.map((item) => (
            <View key={item.reservationId} style={styles.row}>
              <Text style={styles.colWide}>
                {item.guestName}{'\n'}
                {item.propertyName}
              </Text>
              <Text style={styles.col}>
                {item.checkIn}{'\n'}
                {item.checkOut}
              </Text>
              <Text style={styles.colRight}>{fmt(item.revenue, currency)}</Text>
              <Text style={styles.colRight}>{fmt(item.expenses, currency)}</Text>
              <Text style={styles.colRight}>{fmt(item.commission, currency)}</Text>
              <Text style={styles.colRight}>{fmt(item.net, currency)}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by OpenPMS on {new Date().toISOString().split('T')[0]}
        </Text>
      </Page>
    </Document>
  )
}
