-- Seed ICAO countries with names and nationalities in PT, EN, FR
-- ISO 3166-1 alpha-3 codes (used as ICAO nationality codes)

INSERT INTO icao_countries (code, name_pt, name_en, name_fr, nationality_pt, nationality_en, nationality_fr) VALUES
('AFG', 'Afeganistão', 'Afghanistan', 'Afghanistan', 'Afegã', 'Afghan', 'Afghane'),
('ALB', 'Albânia', 'Albania', 'Albanie', 'Albanesa', 'Albanian', 'Albanaise'),
('DZA', 'Argélia', 'Algeria', 'Algérie', 'Argelina', 'Algerian', 'Algérienne'),
('AND', 'Andorra', 'Andorra', 'Andorre', 'Andorrana', 'Andorran', 'Andorrane'),
('AGO', 'Angola', 'Angola', 'Angola', 'Angolana', 'Angolan', 'Angolaise'),
('ATG', 'Antígua e Barbuda', 'Antigua and Barbuda', 'Antigua-et-Barbuda', 'Antiguense', 'Antiguan', 'Antiguaise'),
('ARG', 'Argentina', 'Argentina', 'Argentine', 'Argentina', 'Argentine', 'Argentine'),
('ARM', 'Arménia', 'Armenia', 'Arménie', 'Arménia', 'Armenian', 'Arménienne'),
('AUS', 'Austrália', 'Australia', 'Australie', 'Australiana', 'Australian', 'Australienne'),
('AUT', 'Áustria', 'Austria', 'Autriche', 'Austríaca', 'Austrian', 'Autrichienne'),
('AZE', 'Azerbaijão', 'Azerbaijan', 'Azerbaïdjan', 'Azerbaijana', 'Azerbaijani', 'Azerbaïdjanaise'),
('BHS', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamense', 'Bahamian', 'Bahamienne'),
('BHR', 'Barém', 'Bahrain', 'Bahreïn', 'Bareinita', 'Bahraini', 'Bahreïnienne'),
('BGD', 'Bangladeche', 'Bangladesh', 'Bangladesh', 'Bangladechiana', 'Bangladeshi', 'Bangladaise'),
('BRB', 'Barbados', 'Barbados', 'Barbade', 'Barbadiana', 'Barbadian', 'Barbadienne'),
('BLR', 'Bielorrússia', 'Belarus', 'Biélorussie', 'Bielorrussa', 'Belarusian', 'Biélorusse'),
('BEL', 'Bélgica', 'Belgium', 'Belgique', 'Belga', 'Belgian', 'Belge'),
('BLZ', 'Belize', 'Belize', 'Belize', 'Belizenha', 'Belizean', 'Bélizienne'),
('BEN', 'Benim', 'Benin', 'Bénin', 'Beninense', 'Beninese', 'Béninoise'),
('BTN', 'Butão', 'Bhutan', 'Bhoutan', 'Butanesa', 'Bhutanese', 'Bhoutanaise'),
('BOL', 'Bolívia', 'Bolivia', 'Bolivie', 'Boliviana', 'Bolivian', 'Bolivienne'),
('BIH', 'Bósnia e Herzegovina', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine', 'Bósnia', 'Bosnian', 'Bosnienne'),
('BWA', 'Botsuana', 'Botswana', 'Botswana', 'Botsuanesa', 'Botswanan', 'Botswanaise'),
('BRA', 'Brasil', 'Brazil', 'Brésil', 'Brasileira', 'Brazilian', 'Brésilienne'),
('BRN', 'Brunei', 'Brunei', 'Brunei', 'Bruneíana', 'Bruneian', 'Brunéienne'),
('BGR', 'Bulgária', 'Bulgaria', 'Bulgarie', 'Búlgara', 'Bulgarian', 'Bulgare'),
('BFA', 'Burquina Faso', 'Burkina Faso', 'Burkina Faso', 'Burquinense', 'Burkinabe', 'Burkinabée'),
('BDI', 'Burúndi', 'Burundi', 'Burundi', 'Burundiana', 'Burundian', 'Burundaise'),
('CPV', 'Cabo Verde', 'Cape Verde', 'Cap-Vert', 'Cabo-verdiana', 'Cape Verdean', 'Cap-Verdienne'),
('KHM', 'Camboja', 'Cambodia', 'Cambodge', 'Cambojana', 'Cambodian', 'Cambodgienne'),
('CMR', 'Camarões', 'Cameroon', 'Cameroun', 'Camaronesa', 'Cameroonian', 'Camerounaise'),
('CAN', 'Canadá', 'Canada', 'Canada', 'Canadiana', 'Canadian', 'Canadienne'),
('CAF', 'República Centro-Africana', 'Central African Republic', 'République centrafricaine', 'Centro-africana', 'Central African', 'Centrafricaine'),
('TCD', 'Chade', 'Chad', 'Tchad', 'Chadiana', 'Chadian', 'Tchadienne'),
('CHL', 'Chile', 'Chile', 'Chili', 'Chilena', 'Chilean', 'Chilienne'),
('CHN', 'China', 'China', 'Chine', 'Chinesa', 'Chinese', 'Chinoise'),
('COL', 'Colômbia', 'Colombia', 'Colombie', 'Colombiana', 'Colombian', 'Colombienne'),
('COM', 'Comores', 'Comoros', 'Comores', 'Comorense', 'Comorian', 'Comorienne'),
('COG', 'Congo', 'Congo', 'Congo', 'Congolesa', 'Congolese', 'Congolaise'),
('COD', 'R.D. do Congo', 'DR Congo', 'RD du Congo', 'Congolesa', 'Congolese', 'Congolaise'),
('CRI', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costarriquenha', 'Costa Rican', 'Costaricaine'),
('CIV', 'Costa do Marfim', 'Ivory Coast', 'Côte d''Ivoire', 'Marfinense', 'Ivorian', 'Ivoirienne'),
('HRV', 'Croácia', 'Croatia', 'Croatie', 'Croata', 'Croatian', 'Croate'),
('CUB', 'Cuba', 'Cuba', 'Cuba', 'Cubana', 'Cuban', 'Cubaine'),
('CYP', 'Chipre', 'Cyprus', 'Chypre', 'Cipriota', 'Cypriot', 'Chypriote'),
('CZE', 'Chéquia', 'Czech Republic', 'Tchéquie', 'Checa', 'Czech', 'Tchèque'),
('DNK', 'Dinamarca', 'Denmark', 'Danemark', 'Dinamarquesa', 'Danish', 'Danoise'),
('DJI', 'Djibuti', 'Djibouti', 'Djibouti', 'Djibutiana', 'Djiboutian', 'Djiboutienne'),
('DMA', 'Dominica', 'Dominica', 'Dominique', 'Dominicana', 'Dominican', 'Dominiquaise'),
('DOM', 'República Dominicana', 'Dominican Republic', 'République dominicaine', 'Dominicana', 'Dominican', 'Dominicaine'),
('ECU', 'Equador', 'Ecuador', 'Équateur', 'Equatoriana', 'Ecuadorian', 'Équatorienne'),
('EGY', 'Egito', 'Egypt', 'Égypte', 'Egípcia', 'Egyptian', 'Égyptienne'),
('SLV', 'El Salvador', 'El Salvador', 'Salvador', 'Salvadorenha', 'Salvadoran', 'Salvadorienne'),
('GNQ', 'Guiné Equatorial', 'Equatorial Guinea', 'Guinée équatoriale', 'Guineense equatorial', 'Equatorial Guinean', 'Équato-guinéenne'),
('ERI', 'Eritreia', 'Eritrea', 'Érythrée', 'Eritreia', 'Eritrean', 'Érythréenne'),
('EST', 'Estónia', 'Estonia', 'Estonie', 'Estónia', 'Estonian', 'Estonienne'),
('SWZ', 'Essuatíni', 'Eswatini', 'Eswatini', 'Suázi', 'Swazi', 'Swazie'),
('ETH', 'Etiópia', 'Ethiopia', 'Éthiopie', 'Etíope', 'Ethiopian', 'Éthiopienne'),
('FJI', 'Fiji', 'Fiji', 'Fidji', 'Fijiana', 'Fijian', 'Fidjienne'),
('FIN', 'Finlândia', 'Finland', 'Finlande', 'Finlandesa', 'Finnish', 'Finlandaise'),
('FRA', 'França', 'France', 'France', 'Francesa', 'French', 'Française'),
('GAB', 'Gabão', 'Gabon', 'Gabon', 'Gabonesa', 'Gabonese', 'Gabonaise'),
('GMB', 'Gâmbia', 'Gambia', 'Gambie', 'Gambiana', 'Gambian', 'Gambienne'),
('GEO', 'Geórgia', 'Georgia', 'Géorgie', 'Georgiana', 'Georgian', 'Géorgienne'),
('DEU', 'Alemanha', 'Germany', 'Allemagne', 'Alemã', 'German', 'Allemande'),
('GHA', 'Gana', 'Ghana', 'Ghana', 'Ganesa', 'Ghanaian', 'Ghanéenne'),
('GRC', 'Grécia', 'Greece', 'Grèce', 'Grega', 'Greek', 'Grecque'),
('GRD', 'Granada', 'Grenada', 'Grenade', 'Granadina', 'Grenadian', 'Grenadienne'),
('GTM', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemalteca', 'Guatemalan', 'Guatémaltèque'),
('GIN', 'Guiné', 'Guinea', 'Guinée', 'Guineense', 'Guinean', 'Guinéenne'),
('GNB', 'Guiné-Bissau', 'Guinea-Bissau', 'Guinée-Bissau', 'Guineense', 'Bissau-Guinean', 'Bissau-Guinéenne'),
('GUY', 'Guiana', 'Guyana', 'Guyana', 'Guianense', 'Guyanese', 'Guyanaise'),
('HTI', 'Haiti', 'Haiti', 'Haïti', 'Haitiana', 'Haitian', 'Haïtienne'),
('HND', 'Honduras', 'Honduras', 'Honduras', 'Hondurenha', 'Honduran', 'Hondurienne'),
('HUN', 'Hungria', 'Hungary', 'Hongrie', 'Húngara', 'Hungarian', 'Hongroise'),
('ISL', 'Islândia', 'Iceland', 'Islande', 'Islandesa', 'Icelandic', 'Islandaise'),
('IND', 'Índia', 'India', 'Inde', 'Indiana', 'Indian', 'Indienne'),
('IDN', 'Indonésia', 'Indonesia', 'Indonésie', 'Indonésia', 'Indonesian', 'Indonésienne'),
('IRN', 'Irão', 'Iran', 'Iran', 'Iraniana', 'Iranian', 'Iranienne'),
('IRQ', 'Iraque', 'Iraq', 'Irak', 'Iraquiana', 'Iraqi', 'Irakienne'),
('IRL', 'Irlanda', 'Ireland', 'Irlande', 'Irlandesa', 'Irish', 'Irlandaise'),
('ISR', 'Israel', 'Israel', 'Israël', 'Israelita', 'Israeli', 'Israélienne'),
('ITA', 'Itália', 'Italy', 'Italie', 'Italiana', 'Italian', 'Italienne'),
('JAM', 'Jamaica', 'Jamaica', 'Jamaïque', 'Jamaicana', 'Jamaican', 'Jamaïcaine'),
('JPN', 'Japão', 'Japan', 'Japon', 'Japonesa', 'Japanese', 'Japonaise'),
('JOR', 'Jordânia', 'Jordan', 'Jordanie', 'Jordana', 'Jordanian', 'Jordanienne'),
('KAZ', 'Cazaquistão', 'Kazakhstan', 'Kazakhstan', 'Cazaque', 'Kazakh', 'Kazakhe'),
('KEN', 'Quénia', 'Kenya', 'Kenya', 'Queniana', 'Kenyan', 'Kényane'),
('KIR', 'Quiribáti', 'Kiribati', 'Kiribati', 'Quiribatiana', 'I-Kiribati', 'Kiribatienne'),
('PRK', 'Coreia do Norte', 'North Korea', 'Corée du Nord', 'Norte-coreana', 'North Korean', 'Nord-Coréenne'),
('KOR', 'Coreia do Sul', 'South Korea', 'Corée du Sud', 'Sul-coreana', 'South Korean', 'Sud-Coréenne'),
('KWT', 'Kuwait', 'Kuwait', 'Koweït', 'Kuwaitiana', 'Kuwaiti', 'Koweïtienne'),
('KGZ', 'Quirguistão', 'Kyrgyzstan', 'Kirghizistan', 'Quirguiz', 'Kyrgyz', 'Kirghize'),
('LAO', 'Laos', 'Laos', 'Laos', 'Laociana', 'Laotian', 'Laotienne'),
('LVA', 'Letónia', 'Latvia', 'Lettonie', 'Letã', 'Latvian', 'Lettone'),
('LBN', 'Líbano', 'Lebanon', 'Liban', 'Libanesa', 'Lebanese', 'Libanaise'),
('LSO', 'Lesoto', 'Lesotho', 'Lesotho', 'Lesotiana', 'Basotho', 'Lésothienne'),
('LBR', 'Libéria', 'Liberia', 'Liberia', 'Liberiana', 'Liberian', 'Libérienne'),
('LBY', 'Líbia', 'Libya', 'Libye', 'Líbia', 'Libyan', 'Libyenne'),
('LIE', 'Listenstaine', 'Liechtenstein', 'Liechtenstein', 'Listenstainense', 'Liechtensteiner', 'Liechtensteinoise'),
('LTU', 'Lituânia', 'Lithuania', 'Lituanie', 'Lituana', 'Lithuanian', 'Lituanienne'),
('LUX', 'Luxemburgo', 'Luxembourg', 'Luxembourg', 'Luxemburguesa', 'Luxembourgish', 'Luxembourgeoise'),
('MDG', 'Madagáscar', 'Madagascar', 'Madagascar', 'Malgaxe', 'Malagasy', 'Malgache'),
('MWI', 'Maláui', 'Malawi', 'Malawi', 'Malauiana', 'Malawian', 'Malawienne'),
('MYS', 'Malásia', 'Malaysia', 'Malaisie', 'Malaia', 'Malaysian', 'Malaisienne'),
('MDV', 'Maldivas', 'Maldives', 'Maldives', 'Maldiva', 'Maldivian', 'Maldivienne'),
('MLI', 'Mali', 'Mali', 'Mali', 'Maliana', 'Malian', 'Malienne'),
('MLT', 'Malta', 'Malta', 'Malte', 'Maltesa', 'Maltese', 'Maltaise'),
('MHL', 'Ilhas Marshall', 'Marshall Islands', 'Îles Marshall', 'Marshallina', 'Marshallese', 'Marshallaise'),
('MRT', 'Mauritânia', 'Mauritania', 'Mauritanie', 'Mauritana', 'Mauritanian', 'Mauritanienne'),
('MUS', 'Maurícia', 'Mauritius', 'Maurice', 'Mauriciana', 'Mauritian', 'Mauricienne'),
('MEX', 'México', 'Mexico', 'Mexique', 'Mexicana', 'Mexican', 'Mexicaine'),
('FSM', 'Micronésia', 'Micronesia', 'Micronésie', 'Micronésia', 'Micronesian', 'Micronésienne'),
('MDA', 'Moldávia', 'Moldova', 'Moldavie', 'Moldava', 'Moldovan', 'Moldave'),
('MCO', 'Mónaco', 'Monaco', 'Monaco', 'Monegasca', 'Monegasque', 'Monégasque'),
('MNG', 'Mongólia', 'Mongolia', 'Mongolie', 'Mongol', 'Mongolian', 'Mongole'),
('MNE', 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegrina', 'Montenegrin', 'Monténégrine'),
('MAR', 'Marrocos', 'Morocco', 'Maroc', 'Marroquina', 'Moroccan', 'Marocaine'),
('MOZ', 'Moçambique', 'Mozambique', 'Mozambique', 'Moçambicana', 'Mozambican', 'Mozambicaine'),
('MMR', 'Mianmar', 'Myanmar', 'Myanmar', 'Birmanesa', 'Burmese', 'Birmane'),
('NAM', 'Namíbia', 'Namibia', 'Namibie', 'Namibiana', 'Namibian', 'Namibienne'),
('NRU', 'Nauru', 'Nauru', 'Nauru', 'Nauruana', 'Nauruan', 'Nauruane'),
('NPL', 'Nepal', 'Nepal', 'Népal', 'Nepalesa', 'Nepalese', 'Népalaise'),
('NLD', 'Países Baixos', 'Netherlands', 'Pays-Bas', 'Neerlandesa', 'Dutch', 'Néerlandaise'),
('NZL', 'Nova Zelândia', 'New Zealand', 'Nouvelle-Zélande', 'Neozelandesa', 'New Zealander', 'Néo-Zélandaise'),
('NIC', 'Nicarágua', 'Nicaragua', 'Nicaragua', 'Nicaraguense', 'Nicaraguan', 'Nicaraguayenne'),
('NER', 'Níger', 'Niger', 'Niger', 'Nigerina', 'Nigerien', 'Nigérienne'),
('NGA', 'Nigéria', 'Nigeria', 'Nigeria', 'Nigeriana', 'Nigerian', 'Nigériane'),
('MKD', 'Macedónia do Norte', 'North Macedonia', 'Macédoine du Nord', 'Macedónia', 'Macedonian', 'Macédonienne'),
('NOR', 'Noruega', 'Norway', 'Norvège', 'Norueguesa', 'Norwegian', 'Norvégienne'),
('OMN', 'Omã', 'Oman', 'Oman', 'Omanense', 'Omani', 'Omanaise'),
('PAK', 'Paquistão', 'Pakistan', 'Pakistan', 'Paquistanesa', 'Pakistani', 'Pakistanaise'),
('PLW', 'Palau', 'Palau', 'Palaos', 'Palauense', 'Palauan', 'Palauane'),
('PAN', 'Panamá', 'Panama', 'Panama', 'Panamenha', 'Panamanian', 'Panaméenne'),
('PNG', 'Papua-Nova Guiné', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée', 'Papua-nova-guineense', 'Papua New Guinean', 'Papouane-Néo-Guinéenne'),
('PRY', 'Paraguai', 'Paraguay', 'Paraguay', 'Paraguaia', 'Paraguayan', 'Paraguayenne'),
('PER', 'Peru', 'Peru', 'Pérou', 'Peruana', 'Peruvian', 'Péruvienne'),
('PHL', 'Filipinas', 'Philippines', 'Philippines', 'Filipina', 'Filipino', 'Philippine'),
('POL', 'Polónia', 'Poland', 'Pologne', 'Polaca', 'Polish', 'Polonaise'),
('PRT', 'Portugal', 'Portugal', 'Portugal', 'Portuguesa', 'Portuguese', 'Portugaise'),
('QAT', 'Catar', 'Qatar', 'Qatar', 'Catarense', 'Qatari', 'Qatarienne'),
('ROU', 'Roménia', 'Romania', 'Roumanie', 'Romena', 'Romanian', 'Roumaine'),
('RUS', 'Rússia', 'Russia', 'Russie', 'Russa', 'Russian', 'Russe'),
('RWA', 'Ruanda', 'Rwanda', 'Rwanda', 'Ruandesa', 'Rwandan', 'Rwandaise'),
('KNA', 'São Cristóvão e Neves', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis', 'São-cristovense', 'Kittitian', 'Kittitienne'),
('LCA', 'Santa Lúcia', 'Saint Lucia', 'Sainte-Lucie', 'Santa-lucense', 'Saint Lucian', 'Saint-Lucienne'),
('VCT', 'São Vicente e Granadinas', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les-Grenadines', 'São-vicentina', 'Vincentian', 'Vincentaise'),
('WSM', 'Samoa', 'Samoa', 'Samoa', 'Samoana', 'Samoan', 'Samoane'),
('SMR', 'São Marinho', 'San Marino', 'Saint-Marin', 'São-marinhense', 'Sammarinese', 'Saint-Marinaise'),
('STP', 'São Tomé e Príncipe', 'São Tomé and Príncipe', 'Sao Tomé-et-Príncipe', 'São-tomense', 'São Toméan', 'Santoméenne'),
('SAU', 'Arábia Saudita', 'Saudi Arabia', 'Arabie saoudite', 'Saudita', 'Saudi', 'Saoudienne'),
('SEN', 'Senegal', 'Senegal', 'Sénégal', 'Senegalesa', 'Senegalese', 'Sénégalaise'),
('SRB', 'Sérvia', 'Serbia', 'Serbie', 'Sérvia', 'Serbian', 'Serbe'),
('SYC', 'Seicheles', 'Seychelles', 'Seychelles', 'Seichelense', 'Seychellois', 'Seychelloise'),
('SLE', 'Serra Leoa', 'Sierra Leone', 'Sierra Leone', 'Serra-leonesa', 'Sierra Leonean', 'Sierra-Léonaise'),
('SGP', 'Singapura', 'Singapore', 'Singapour', 'Singapurense', 'Singaporean', 'Singapourienne'),
('SVK', 'Eslováquia', 'Slovakia', 'Slovaquie', 'Eslovaca', 'Slovak', 'Slovaque'),
('SVN', 'Eslovénia', 'Slovenia', 'Slovénie', 'Eslovena', 'Slovenian', 'Slovène'),
('SLB', 'Ilhas Salomão', 'Solomon Islands', 'Îles Salomon', 'Salomónica', 'Solomon Islander', 'Salomonaise'),
('SOM', 'Somália', 'Somalia', 'Somalie', 'Somali', 'Somali', 'Somalienne'),
('ZAF', 'África do Sul', 'South Africa', 'Afrique du Sud', 'Sul-africana', 'South African', 'Sud-Africaine'),
('SSD', 'Sudão do Sul', 'South Sudan', 'Soudan du Sud', 'Sul-sudanesa', 'South Sudanese', 'Sud-Soudanaise'),
('ESP', 'Espanha', 'Spain', 'Espagne', 'Espanhola', 'Spanish', 'Espagnole'),
('LKA', 'Sri Lanca', 'Sri Lanka', 'Sri Lanka', 'Cingalesa', 'Sri Lankan', 'Sri-Lankaise'),
('SDN', 'Sudão', 'Sudan', 'Soudan', 'Sudanesa', 'Sudanese', 'Soudanaise'),
('SUR', 'Suriname', 'Suriname', 'Suriname', 'Surinamesa', 'Surinamese', 'Surinamaise'),
('SWE', 'Suécia', 'Sweden', 'Suède', 'Sueca', 'Swedish', 'Suédoise'),
('CHE', 'Suíça', 'Switzerland', 'Suisse', 'Suíça', 'Swiss', 'Suisse'),
('SYR', 'Síria', 'Syria', 'Syrie', 'Síria', 'Syrian', 'Syrienne'),
('TJK', 'Tajiquistão', 'Tajikistan', 'Tadjikistan', 'Tajique', 'Tajik', 'Tadjike'),
('TZA', 'Tanzânia', 'Tanzania', 'Tanzanie', 'Tanzaniana', 'Tanzanian', 'Tanzanienne'),
('THA', 'Tailândia', 'Thailand', 'Thaïlande', 'Tailandesa', 'Thai', 'Thaïlandaise'),
('TLS', 'Timor-Leste', 'Timor-Leste', 'Timor oriental', 'Timorense', 'Timorese', 'Timoraise'),
('TGO', 'Togo', 'Togo', 'Togo', 'Togolesa', 'Togolese', 'Togolaise'),
('TON', 'Tonga', 'Tonga', 'Tonga', 'Tonganesa', 'Tongan', 'Tongienne'),
('TTO', 'Trindade e Tobago', 'Trinidad and Tobago', 'Trinité-et-Tobago', 'Trinitária', 'Trinidadian', 'Trinidadienne'),
('TUN', 'Tunísia', 'Tunisia', 'Tunisie', 'Tunisina', 'Tunisian', 'Tunisienne'),
('TUR', 'Turquia', 'Turkey', 'Turquie', 'Turca', 'Turkish', 'Turque'),
('TKM', 'Turquemenistão', 'Turkmenistan', 'Turkménistan', 'Turcomana', 'Turkmen', 'Turkmène'),
('TUV', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvaluana', 'Tuvaluan', 'Tuvaluane'),
('UGA', 'Uganda', 'Uganda', 'Ouganda', 'Ugandesa', 'Ugandan', 'Ougandaise'),
('UKR', 'Ucrânia', 'Ukraine', 'Ukraine', 'Ucraniana', 'Ukrainian', 'Ukrainienne'),
('ARE', 'Emirados Árabes Unidos', 'United Arab Emirates', 'Émirats arabes unis', 'Emiradense', 'Emirati', 'Émirienne'),
('GBR', 'Reino Unido', 'United Kingdom', 'Royaume-Uni', 'Britânica', 'British', 'Britannique'),
('USA', 'Estados Unidos', 'United States', 'États-Unis', 'Americana', 'American', 'Américaine'),
('URY', 'Uruguai', 'Uruguay', 'Uruguay', 'Uruguaia', 'Uruguayan', 'Uruguayenne'),
('UZB', 'Uzbequistão', 'Uzbekistan', 'Ouzbékistan', 'Uzbeque', 'Uzbek', 'Ouzbèke'),
('VUT', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatuana', 'Ni-Vanuatu', 'Vanuatuane'),
('VAT', 'Vaticano', 'Vatican City', 'Vatican', 'Vaticana', 'Vatican', 'Vaticane'),
('VEN', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuelana', 'Venezuelan', 'Vénézuélienne'),
('VNM', 'Vietname', 'Vietnam', 'Viêt Nam', 'Vietnamita', 'Vietnamese', 'Vietnamienne'),
('YEM', 'Iémen', 'Yemen', 'Yémen', 'Iemenita', 'Yemeni', 'Yéménite'),
('ZMB', 'Zâmbia', 'Zambia', 'Zambie', 'Zambiana', 'Zambian', 'Zambienne'),
('ZWE', 'Zimbábue', 'Zimbabwe', 'Zimbabwe', 'Zimbabueana', 'Zimbabwean', 'Zimbabwéenne'),
('PSE', 'Palestina', 'Palestine', 'Palestine', 'Palestina', 'Palestinian', 'Palestinienne'),
('XKX', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovar', 'Kosovar', 'Kosovare'),
('TWN', 'Taiwan', 'Taiwan', 'Taïwan', 'Taiwanesa', 'Taiwanese', 'Taïwanaise'),
('HKG', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Hong-konguesa', 'Hong Konger', 'Hongkongaise'),
('MAC', 'Macau', 'Macau', 'Macao', 'Macaense', 'Macanese', 'Macanaise');
